@hostname=luchang.xyz

### 静态网页
GET http://{{hostname}}


### getNameById
GET http://{{hostname}}/getnamebyId?id=17081103

### string post test
POST http://{{hostname}}/updateNameById
Content-Type: application/json

{
  "name":"luchang",
  "id":23
}

### change name to new name
POST http://{{hostname}}/updateNameById
Content-Type: application/json

{
  "id":17081103,
  "name":"new name"
}

### change name to default
POST http://{{hostname}}/updateNameById
Content-Type: application/json

{
  "id":17081103,
  "name":"luchang"
}